shellEmulator: true

catalogs:
  r:
    'comark': ^0.6.2
    'smol-toml': ^1.8.0
  x:
    '@vitest/coverage-v8': ^4.1.10
    'oxfmt': ^0.51.0
    'oxlint': ^1.78.0
    'oxlint-tsgolint': '^7.0.2001'
    'tsdown': ^0.22.14
    'vitest': ^4.1.10
  t:
    '@types/markdown-it': ^14.1.2
    '@types/node': ^26.2.0
